# job status definitions
QUEUED = 'QUEUED'
RUNNING = 'RUNNING'
COMPLETE = 'COMPLETE'
FAILED = 'FAILED'
TIMED_OUT = 'TIMED_OUT'

# sub status
WAITING_FOR_TRANSFER_COMPLETION = 'WAITING_FOR_TRANSFER_COMPLETION'
WAITING_FOR_ADAMS_START = 'WAITING_FOR_ADAMS_START'
MONITORING_ADAMS_LOG = 'MONITORING_ADAMS_LOG'
INITIALIZED = 'INITIALIZED'

# run modes
RUN_TEST = 'RUN_TEST'
RUN_TEST_STATIC = 'RUN_TEST_STATIC'
RUN_TEST_TRANSFER_WAIT = 'RUN_TEST_TRANSFER_WAIT'
RUN_PROD = 'RUN_PROD'

# run settings
SPOOF_SINGLE = 'SPOOF_SINGLE'
SPOOF_DOE = 'SPOOF_DOE'
SPOOF_RUN_TIME = 8
RUN_SINGLE = 'RUN_SINGLE'
RUN_DOE = 'RUN_DOE'
ADAMS_START_LIMIT = 60
ADAMS_FINISH_LIMIT = 60 * 60

DOE_COMPLETE_STRING = 'RUNSTUDY COMPLETE'
SINGLE_COMPLETE_STRING = 'Information: Model creation complete'

# feature test sentinels
TEST_TRANSFER_WAIT = False
TEST_QUE_MOD = False
TEST_QUE_ADD = False